### ISSUE TITLE
Unable to update the windows context-menu synchronously

### ISSUE THREAD

**Issue by dnknn** [hexandcube/desktop-icon-toggle#1]
Hi_:) Thank you for your this gadget !!

### Unable to update the windows context-menu synchronously

- This is not a big problem at first, but if this is the case 👇 
![image](https://user-images.githubusercontent.com/10995302/128705656-c8797880-ceff-4bce-b55c-ab1afa927a8e.png)

you will not be able to rename (`F2`) the name of the desktop icon.

But based on this principle, we can manual correction/fix: [image](https://user-images.githubusercontent.com/10995302/128705936-a26b7381-a3fd-43d4-9505-20903d76cd11.png) , only then can it be renamed ^_^

---------------------------------------------------------------------
　　　

I don't understand the code, detailed situation/solution/workaround, see here [image](https://user-images.githubusercontent.com/10995302/128707699-39817cbe-2ff6-423a-9cee-fcdf797b5f93.png): 👇 

https://github.com/rocksdanister/lively/issues/663#issuecomment-894999615

If the ContextMenu is updated synchronously, and it will not cause performance problems, then it is worth it, otherwise please ignore this issue ^_^

> This is not a big problem, I only report such cases  ^_^

**Comment by hexandcube** [comment]
Thanks for reporting! I didn't notice that until now. I'm gonna look into it when I come back from vacation.

**Comment by hexandcube** [comment]
I managed to fix the issue. The fix will be in the 1.2 version.

**Comment by hexandcube** [comment]
The issue has been fixed! The new version with the fix implemented (1.2.0) is now available:

https://github.com/hexandcube/desktop-icon-toggle/releases/tag/v.1.2.0

**Comment by dnknn** [comment]
🤝ThankYouVeryMuch!
