### ISSUE TITLE
Bug: Icons/folders on the desktop cannot be `clicked`/`double-clicked`(open)

### ISSUE THREAD

**Issue by dnknn** [hexandcube/desktop-icon-toggle#2]
`desktop-icon-toggle` is not compatible with `LivelyWallpaper` ...😭-_-😢

- Scenario to reproduce the problem: (Win10)
	1) ![61238f0](https://user-images.githubusercontent.com/10995302/130504648-c9c4a20e-79d8-4424-bf57-380639573584.jpg)	Install LivelyWallpaper: https://github.com/rocksdanister/lively/releases#:~:text=.exe
	2) Choose the live wallpaper provided by default  [image](https://user-images.githubusercontent.com/10995302/130504966-7110e5f0-5bc5-48c8-848e-34453e8ddf2b.png) to test, only a small part is compatible with your program (you can click on the desktop icon).
	3) or, of course, you can also use HTML5 pages 👇 to test the problem.
[25th_hour.zip](https://github.com/hexandcube/desktop-icon-toggle/files/7034401/25th_hour.zip) (After extracting Use) 👈 From https://louie.co.nz/25th_hour/

**Comment by dnknn** [comment]
This is a Lively issue , sorry...!

**Comment by dnknn** [comment]
![image](https://user-images.githubusercontent.com/10995302/130658010-a335835e-1275-44cc-b629-ea40b847985b.png)


But if I pause/exit your program, then everything is normal,
In other words, if don't use your program, in fact, `Lively` will not happen this problem.

So, can you test and see (if you have time) ...^_^

> tips: If pause/exit your program, `Lively` itself by turning on Wallpaper Input (🖱Mouse interaction) [image](https://user-images.githubusercontent.com/10995302/130659272-79d11850-6f46-47de-8e5a-385d256d9f1c.png)
 , itself is no problem,

**Comment by hexandcube** [comment]
Hey, thanks for the report! 
Unfortunately, I wasn't able to replicate the issue. On my end, Desktop Icon Toggle seems to work fine with Lively.
I tried all built-in Wallpapers, and the HTML 5 page you sent me.

Maybe I'm misunderstanding something. Could you provide a screen recording of the issue?

**Comment by dnknn** [comment]
> Could you provide a screen recording of the issue?

Due to github limitation ⩽10㎆ , So I uploaded to Google Drive

https://drive.google.com/drive/folders/18PCYM1KeaHJbwWmCEpximKLf2k1UpddO?usp=sharing

**Comment by hexandcube** [comment]
Unfortunately, I still cannot replicate this issue. If someone manages to replicate it, let me know.

**Comment by dnknn** [comment]
@hexandcube Hi, see at: https://github.com/rocksdanister/lively/issues/687#issuecomment-913617278
