### ISSUE TITLE
Toggle does not work over hidden icons

### ISSUE THREAD

**Issue by csc530** [hexandcube/desktop-icon-toggle#3]
When I double-click an _empty_ space on the desktop, the visibility of my icons won't change if that position has an icon.

For example, on my desktop below...
![image](https://user-images.githubusercontent.com/77406318/221680795-8af17390-e267-4a41-8cb2-5c521cd45a4d.png)

![image](https://user-images.githubusercontent.com/77406318/221681106-a5c8ee59-43f5-4b2a-9f78-d13a903fd0e7.png)

If I try double-clicking in the circled area where the _GitHub Desktop icon_ would be, the visibility won't toggle.
I hope that makes sense.

---

> double-clicking the blank space on the desktop
> — From ReadMe

I'm not sure if you meant blank, even when hidden too
If so, I'll just decrease my icons size😅

**Comment by csc530** [comment]
I made a pull request (#4) which I tested and believe should fix this issue

**Comment by hexandcube** [comment]
Fixed in version 1.4 (https://github.com/hexandcube/desktop-icon-toggle/releases/tag/v.1.4)
